### PR TITLE
LPS-98418 Update Dev Guide on liferay-docs

### PR DESCRIPTION
**Pull request by gabrielibson**

### CODE REVIEW

**Comment by gabrielibson** [comment]
Related issue: https://issues.liferay.com/browse/LPS-98418

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-docs/pull/37. [See changes here.](https://github.com/natocesarrego/liferay-docs/compare/59d940420~1...59d940420) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/rbohl/liferay-docs/pull/162. [See changes here.](https://github.com/natocesarrego/liferay-docs/compare/0a34fcee2~2...0a34fcee2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
